version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: npm run coverage
      - run:
          name: Codecov upload
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
